version: "3.9"
services:
  backend:
    build:
      context: ./backend
    image: geo-portfolio-backend
    environment:
      - PUBLIC_BASE_URL=http://localhost:8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["python", "app.py"]

  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules   # <- cache deps between runs
    command: bash -lc "npm i && npm run dev -- --host"

volumes:
  node_modules:
